import React from 'react';
import StoryItem from './StoryItem';
import hulu7 from '../public/hulu2007.png';
import hulu8 from '../public/hulu2008.jpg';
import hulu9 from '../public/hulu2009.jpg';
import hulu10 from '../public/hulu2010.jpg';
import hulu11 from '../public/hulu2011.jpg';
import hulu12 from '../public/hulu2012.jpg';
import hulu13 from '../public/hulu2013.png';
import hulu14 from '../public/hulu2014.jpg';
import hulu15 from '../public/hulu2015.jpg';
import hulu16 from '../public/hulu2016.jpg';
import hulu17 from '../public/hulu2017.jpg';
import hulu19 from '../public/hulu2019.jpg';
import hulu20 from '../public/hulu2020.png';

const stories = [
    {year: "2007", title: "Hulu is Founded", direction: "flex-row", image: hulu7, imageHeight: 980, imageWidth: 1920, paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-left", animatePara: "fade-right"},
    {year: "2008", title: "", direction: "flex-row-reverse", image: hulu8, imageHeight: 980, imageWidth: 1920, paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-right", animatePara: "fade-left"},
    {year: "2009", title: "Hulu first Super Bowl ad airs", direction: "flex-col", image: hulu9, imageHeight: 580, imageWidth: 1580, paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-right", animatePara: "fade-left"},
    {year: "2010", title: "Hulu launchs subcriptions service", direction: "flex-col-reverse", image: hulu10, imageHeight: 980, imageWidth: 1920, paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "flip-right", animatePara: "zoom-in-up"},
    {year: "2011", title: "A day in a life", direction: "flex-col", image: hulu11, imageHeight: 580, imageWidth: 1580, paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "zoom-in-right", animatePara: "flip-left"},
    {year: "2012", title: "Hits 1 million subscribers", direction: "flex-row-reverse", image: hulu12, imageHeight: 980, imageWidth: 1920, paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "zoom-out-up", animatePara: "fade-down-left"},
    {year: "2013", title: "Showtime becomes the first premium", direction: "flex-col", image: hulu13, imageHeight: 380, imageWidth: 1580, paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-right", animatePara: "fade-left"},
    {year: "2014", title: "Hulu gives subscribers more choice", direction: "flex-row-reverse", image: hulu14, imageHeight: 980, imageWidth: 1920, paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-right", animatePara: "fade-left"},
    {year: "2015", title: "Hits 10 million subscribers", direction: "flex-row", image: hulu15, imageHeight: 980, imageWidth: 1920, paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-right", animatePara: "fade-left"},
    {year: "2016", title: "Hulu goes live with Live TV", direction: "flex-col", image: hulu16, imageHeight: 580, imageWidth: 1580, paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "zoom-out", animatePara: "flip-right"},
    {year: "2017", title: "Becomes the first streaming service", direction: "flex-row-reverse", image: hulu17, imageHeight: 980, imageWidth: 1920, paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-right", animatePara: "fade-left"},
    {year: "2018", title: "Hulu celebrates 10 years", direction: "flex-col-reverse", image: hulu10, imageHeight: 980, imageWidth: 1920, paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "fade-right", animatePara: "fade-left"},
    {year: "2019", title: "Walt Disney Company assumes full operational control of Hulu", direction: "flex-col", image: hulu19, imageHeight: 580, imageWidth: 1580, paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "zoom-out-down", animatePara: "flip-left"},
    {year: "2020", title: "The TMDb product, service, attitude and support are truly top notch", direction: "flex-row", image: hulu20, imageHeight: 1780, imageWidth: 1920, paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", animateImage: "zoom-out-up", animatePara: "fade-up-right"},
];

function Story() {
    return (
        <div className="px-20 my-5 bg-white">
            {
                stories.map((story, index) => {
                    return <StoryItem key={index} story={story} />
                })
            }
        </div>
    )
}

export default Story;
